### PR TITLE
mySQL 5.7 compatibility, add sortfield in distinct select

### PR DESCRIPTION
**Pull request by jonmifsud**
It seems like mySQL 5.7.10 throws errors everytime there is a distinct with a sort clause where the sort is not included in the select, this just adds the sort order within the query select statement.

### CODE REVIEW

**Comment by brendo** [comment]
I've been noticing this as well. You can disable it at a server level if you need to, which is ultimately what I did.

**Comment by jonmifsud** [comment]
So far I only encountered two places where I need to make this fix, this
and one in the core.

I'm not sure if it's best practice that we start asking people to disable
things from MySQL so making small changes like this might make sense in the
long term.

**Comment by brendo** [comment]
> I'm not sure if it's best practice that we start asking people to disable
> things from MySQL so making small changes like this might make sense in the
> long term.

Oh definitely, I'm not suggesting we do, but if you're in a pinch now that's a solution :)

**Comment by jonmifsud** [comment]
Ah :) yeah it's kinda working now I made a fix yesterday to the core - not
sure it's great but works locally so far. I'd like to go through a few more
of the sites to ensure that all the sites/functionality are working as they
should before submitting it as a PR. It's only on my local setup right now
so not a prod issue, that's a bit more behind.

**Comment by jonmifsud** [comment]
@nitriques any chance we could release this? very minor fix.

**Comment by nitriques** [comment]
@jonmifsud please create an entry in the meta.xml file and I'll release ASAP ! Thanks!

**Comment by jonmifsud** [comment]
@nitriques I've bumped the version and added a new delegate. I might be re-thinking my previous version for the 'association' filtering drawer. 

The new delegate is mainly used for relationship filtering - when there are permissions and doing that via other means is not secure if you have multiple users on the same backend. I might want to give some more thought on other changes - including core ones on previous pull requests maybe I figure out a cleaner way of doing it.

**Comment by nitriques** [comment]
Ok. But should I release this?

**Comment by jonmifsud** [comment]
@nitriques this should be fine.

**Comment by nitriques** [comment]
16e1c30 was sitting in integration which is basically the same fix as eb463ba.

Cherry picked 806fb97 as c886dca. Released as `1.1.0`. Thanks. Sorry for the mega delay.

**Pull request closed without merging**
